#!/usr/bin/env bash
# PlayOnAir container entrypoint.
#
# On Home Assistant OS, Supervisor mounts /data/options.json from the Configuration tab.
# That file is the source of truth: we regenerate $PLAY_ON_AIR_CONFIG (TOML) on every start
# and set RUST_LOG from log_level when RUST_LOG is not already set.
#
# Standalone docker (no options.json): skip generation and exec the binary with product defaults.

set -eu

OPTIONS_FILE="${OPTIONS_FILE:-/data/options.json}"
CONFIG_PATH="${PLAY_ON_AIR_CONFIG:-/config/play-on-air.toml}"

write_toml_from_options() {
  local options_file="$1"
  local config_path="$2"
  local config_dir
  local log_level

  if ! jq -e . "${options_file}" >/dev/null 2>&1; then
    echo "play-on-air: options file is missing or not valid JSON: ${options_file}" >&2
    exit 1
  fi

  if ! jq -e 'type == "object"' "${options_file}" >/dev/null 2>&1; then
    echo "play-on-air: options root must be a JSON object: ${options_file}" >&2
    exit 1
  fi

  if [[ -z "${RUST_LOG:-}" ]]; then
    log_level="$(jq -r '.log_level // "info"' "${options_file}")"
    case "${log_level}" in
      trace | debug | info | warn | error) ;;
      *)
        echo "play-on-air: invalid log_level '${log_level}' (expected trace|debug|info|warn|error)" >&2
        exit 1
        ;;
    esac
    export RUST_LOG="${log_level}"
  fi

  config_dir="$(dirname "${config_path}")"
  mkdir -p "${config_dir}"

  {
    echo "# Generated by PlayOnAir from Home Assistant Configuration options."
    echo "# Do not edit by hand while using the Configuration tab — overwritten on each start."
    echo "#"
    echo "# Optional cosmetics only. Empty devices list → product defaults (identity names, nothing hidden)."
    echo ""
    # shellcheck disable=SC2016
    jq -r '
      (.devices // []) as $devices
      | if ($devices | length) == 0 then
          empty
        else
          $devices[]
          | (
              "[[device]]",
              "id = " + (.id // "" | @json),
              (if ((.name // "") | length) > 0 then "name = " + (.name | @json) else empty end),
              (if .hide == true then "hide = true" else empty end),
              ""
            )
        end
    ' "${options_file}"
  } >"${config_path}"
}

if [[ -f "${OPTIONS_FILE}" ]]; then
  write_toml_from_options "${OPTIONS_FILE}" "${CONFIG_PATH}"
fi

exec play-on-air --config "${CONFIG_PATH}"
